#options(repos = c(CRAN = 'https://cran.rstudio.com/'))
install.packages("dplyr")
install.packages("readr")
install.packages("stringr")
install.packages("purrr")
install.packages("forecats")
install.packages("here")
install.packages("yaml")
install.packages("synthpop")
install.packages("recipes")
install.packages("rsample")
install.packages("parsnip")
install.packages("workflows")
install.packages("tune")
install.packages("yardstick")