name: Run Modeling Pipeline
on: push
jobs:
  run:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.2'
            
      - name: Setup dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libxml2-dev
          R -e 'install.packages("renv")' 
          R -e 'renv::restore()'
          
      - name: Run experiment
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          dvc repro
