name: Run Modeling Pipeline
on: push
jobs:
  run_pipeline:
    name: Run Modeling Pipeline
    runs-on: [ubuntu-20.04]
    container: jdegregorio/mlops-model-registry-concept:latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
          
      - name: Run experiment
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          dvc repro